### ISSUE TITLE
Empty stats

### ISSUE THREAD

**Issue by janmechtel** [janmechtel/rockettype#30]
1. Seems like the log file is now stored in `%USERPROFILE%\outputs`
let's change this to `%USERPROFILE%\RocketType`

2. My stats are empty:

![image](https://user-images.githubusercontent.com/1004314/92278721-1a5eb000-eef6-11ea-9772-ddad1d54e949.png)

`exceptions.txt` shows:

> ""name 'logger_stats' is not defined"" I time i call it

**Comment by appins** [comment]
For the specific error, could you try uninstalling and reinstalling? Sometimes old files get left / not replaced if you install without uninstalling first. At some point, we should get a better flow for updates and such, but for now, files are moving around constantly. 

Let me know if the issue persists, as I am getting no such issue. (also, if you're getting it with the installed version or only the version running out of the repository folder, etc).

**Comment by janmechtel** [comment]
I haven't tried installing, but now i have this issue when running from debugger.

The RocketType/key_log.txt is created and filled with the header row, but now keys are logged into it after wards.

**Comment by appins** [comment]
Yes @janmechtel, its a form of caching that is built into operating systems or python. The keystrokes should begin to appear in the file every 60 seconds or so. It might delay the initial collection of stats but massively reduces the amount of time to log keystrokes (Can capture up to >350 WPM, from my tests). 

This is a side effect of opening a file and writing to it rather than setting the logger to that file.

**Comment by janmechtel** [comment]
Ok I will test it now. We should still find a better solution for this,
maybe we just ad it to the explanation, as the recommendation in the stats
window is to delete the file, which will not help.

Also when I'm debugging sometimes/often the stats window shows immediately,
is that intentional?

**Comment by janmechtel** [comment]
Ok this is working, I was just too impatient for the stats.
